### PR TITLE
Changed the animation directions

### LINKED ISSUE #73: Animation direction
**Describe the bug**
At the moment all the animations in the site have the same direction.

**Expected behavior**
Change animations to different directions

**Are you working on it?**
Yes

### PR DESCRIPTION
**Pull request by SilunaP**
## Purpose
The purpose of this Pull Request is to fix #73 

## Goals
This changes the same animations directions of the texts in to different animation directions.

## Approach
Changing the javascript file and using css.
  
##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: assets/js/app.js [hunk 1]
```diff
@@ -9,5 +9,8 @@ const observer = new IntersectionObserver((entries) => {
...
 });
 
-const hiddenElements = document.querySelectorAll('.hidden');
-hiddenElements.forEach((el) => observer.observe(el));
\ No newline at end of file
+const hiddenElementsRight = document.querySelectorAll('.d-right');
+hiddenElementsRight.forEach((el) => observer.observe(el));
+
+const hiddenElementsLeft = document.querySelectorAll('.d-left');
+hiddenElementsLeft.forEach((el) => observer.observe(el));
```
Comment (YoshithaRathnayake) [inline assets/js/app.js]: @SilunaP brother add a new line at the bottom of the file

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
@SilunaP brother can you update the preview link with the following steps,

- First, go to your forked repository. Then click on the settings tab and click the pages tab in the settings. After that go to the Branch section in the pages tab and click the 'None' dropdown and there you can see the branches you pushed the changes. Select the necessary branch and click save.
-  Once you submit the PR, replace "YOUR_USERNAME" with your GitHub Account Username. And replace the "FORKED_REPO_NAME" with your forked repository name.
-  ex: https://care-x.github.io/landing-page/
-  Feel free to modify the link with the exact path
https://YOUR_USERNAME.github.io/FORKED_REPO_NAME/

File: assets/js/app.js (hunk 1 above)
Comment (SilunaP) [reply assets/js/app.js]: ok
